"""Update model classes

Revision ID: 6e820d07d39c
Revises: e1ce83ce683a
Create Date: 2022-05-17 19:53:31.183155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e820d07d39c'
down_revision = 'e1ce83ce683a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscriber_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subscribers', ['subscriber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscriber_id')
    # ### end Alembic commands ###
